## Define your own functions

The most basic example

In [15]:
def say_hello():

    #This function says Hello!
    print("Hello")

In [16]:
say_hello()

Hello


A function with one varible

In [27]:
def say_hello(name):

    #This function says Hello and the value on the local variable "name"

    print("Hello" , name , "!")

In [28]:
say_hello("Adele")

Hello Adele !


A function with two varibles

In [25]:
def say_hello(name, surname):

    #This function says Hello and the value on the local variables: "name" and "surname"

    print("Hello" , name , surname, "!")

In [24]:
say_hello("Adele", "Smith")

Hello Adele Smith  !


## If Clause

Conditionals are a very useful tool for coding. 
It helps us separate different situations or coding flows.

In [29]:
def is_positive(number):
    #This function tells you if a number is positive

    if number > 0:
        print("The ", number, " is a positive number.")
    print("This is always printed.")

In [30]:
is_positive(5)

The  5  is a positive number.
This is always printed.


In [31]:
is_positive(-1)

This is always printed.


We can complete the if clause by adding the else condition. 
If the if clause is false, the code will continue in the else block

In [33]:
def sign(number):
    #This function tells you if a number is positive or negative

    if number >= 0:
        print("The ", number, " is a positive number or zero.")
    else:
        print("The ", number, " is a negative number.")
    print("This is always printed.")

Sometimes we want to add more than two options in our code, so we need to use the elif clause.
First of all, we will see if the condition is true. If it is false, the code will evaluate the elif conditions. If the elif condition is true, the code will evaluate that block. If all the conditions are false, it will evaluate the else block.

In [3]:
def sign(number):

    #This function tells you if a number is positive, negative or zero

    if number > 0:
        print("The ", number, " is a positive number or zero.")
    elif number==0:
        print("This is zero!")
    else:
        print("The ", number, " is a negative number.")
    print("This is always printed.")

In [4]:
sign(5)

The  5  is a positive number or zero.
This is always printed.


In [5]:
sign(-1)

The  -1  is a negative number.
This is always printed.


In [6]:
sign(0)

This is zero!
This is always printed.


## For Clause

We learned to count when we were children. The for loop is very convenient for counting, but also for moving through the positions of vectors and matrices.

In [7]:
def counting(start, stop):

    #This function counts from start to stop (not included)

    for i in range(start, stop):
        print(i)
    print("This is always printed.")

In [8]:
counting(1, 5)

1
2
3
4
This is always printed.


A practical example of how to use the for clause to do a calculation such as the factorial.

In [10]:
def factorial(n):

    #This function calculates the factorial

    #The initialise the variable factorial
    factorial=1;

    #By using the for iteratively, we compute the factorial
    for i in range(2,n+1):
        factorial=factorial*i

    print(factorial)


In [11]:
factorial(3)

6


In [12]:
factorial(10)

3628800


## Matrices

We create a Matrix as a list of list, i.e. vector by vector

In [14]:
A = [[1, 2, 3], 
    [-4, -5, -6],
    [7, 8, 9]]

We can print the whole structure

In [16]:
print("A =", A) 

A = [[1, 2, 3], [-4, -5, -6], [7, 8, 9]]


Chose the 2nd row

In [17]:
print("A[1] =", A[1])

A[1] = [-4, -5, -6]


Chose an element, for example, 3rd element 3rd row

In [18]:
print("A[2][2] =", A[2][2])

A[2][2] = 9


Chose the last element of the 2nd row

In [19]:
print("A[0][-1] =", A[1][-1])

A[0][-1] = -6


We create a new empty list

In [20]:
column = [];        
for row in A:
    
    #We allocate the second column row by row
    column.append(row[2]) 

We print the 3rd column

In [21]:
print("3rd column =", column)

3rd column = [3, -6, 9]


-- We can use numpy to create numerical matrices

In [23]:
#Load numpy package
import numpy as np

#Create an array
A = np.array([[1, 2, 3], 
    [-4, -5, -6],
    [7, 8, 9]])

Print the matrix

In [24]:
print("A=",A)

A= [[ 1  2  3]
 [-4 -5 -6]
 [ 7  8  9]]


Print the second column

In [25]:
print("2nd column", A[:,1])

2nd column [ 2 -5  8]


-- With Numpy, we can create a matrix full of zeros

In [26]:
#Load numpy package
import numpy as np

#Create matrix full of zeros
A = np.zeros((3,3))

#Print the matrix
print("A=",A)

A= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Or full of ones

In [27]:
#Load numpy package
import numpy as np

#Create matrix full of ones
A = np.ones((3,3))

#Print the matrix
print("A=",A)

A= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Or just ones in the diagonal

In [28]:
#Create matrix with ones on the diagonal
B = np.diag(np.ones(3))  

#Print the matrix
print("B=",B)

B= [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


An example to fill an array with different values

In [29]:
#Load numpy package
import numpy as np

#Create matrix full of ones
A = np.zeros((3,4))

#Print the matrix
print("A=",A)

#Print the shape of the matrix
print("The matrix shape is", A.shape)

#We define the variable count
count=1

#For each row
for i in range(0, A.shape[0]):
    
    #For each position
    for j in range(0, A.shape[1]):
        
        #Write in the position [i,j] the variable count
        A[i,j]=count
        
        #Sum 1 to count
        count=count+1

#Print the matrix
print("A=",A)

A= [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
The matrix shape is (3, 4)
A= [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
